adding nginx new relic agent

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -2,10 +2,7 @@
 # bin/compile <build-dir> <cache-dir>
 
 set -e            # fail fast
-set -o pipefail   # don't ignore exit codes when piping output
-
-# Ubuntu version
-release=`lsb_release -cs`
+set -o pipefail   # do not ignore exit codes when piping output
 # set -x          # enable debugging
 
 # Configure directories
@@ -13,15 +10,17 @@ build_dir=$1
 cache_dir=$2
 
 # Version
-nginx_version="1.7.10.1"
+nginx_version="1.7.10"
 
 compile_buildpack_dir=$(cd $(dirname $0); cd ..; pwd)
 compile_buildpack_bin=$compile_buildpack_dir/bin
+$compile_buildpack_dir/compile-extensions/bin/check_stack_support
 
 # Load some convenience functions like status(), echo(), and indent()
 source $compile_buildpack_dir/bin/common.sh
 
-compile_nginx_tgz="$compile_buildpack_dir/vendor/nginx-$nginx_version-$release.tar.gz"
+$compile_buildpack_dir/compile-extensions/bin/download_dependency nginx-$nginx_version.tar.gz /tmp
+compile_nginx_tgz="/tmp/nginx-$nginx_version.tar.gz"
 cd $build_dir
 
 # Alternate root location (default is root of project) for html/js/css
@@ -41,17 +40,15 @@ rsync -a \
       --exclude='/Staticfile.auth' \
       --exclude='/manifest.yml' \
       --exclude='/stackato.yml' \
-      --exclude='/*.lua' \
       $root_dir/ $build_dir/public
 
 status "Setting up nginx"
 tar xzf $compile_nginx_tgz
+cp -f $compile_buildpack_dir/conf/nginx.conf nginx/conf/nginx.conf
+cp -f $compile_buildpack_dir/conf/mime.types nginx/conf/mime.types
 
-cp -f $compile_buildpack_dir/conf/nginx.conf openresty/nginx/conf/nginx.conf
-cp -f $compile_buildpack_dir/conf/mime.types openresty/nginx/conf/mime.types
-cp -f $compile_buildpack_dir/conf/gzip.types openresty/nginx/conf/gzip.types
-
-mkdir -p openresty/nginx/cache/tmp
+[[ -f $build_dir/public/nginx.conf ]] && mv $build_dir/public/nginx.conf nginx/conf/nginx.conf
+[[ -f $build_dir/public/mime.types ]] && mv $build_dir/public/mime.types nginx/conf/mime.types
 
 if [[ -f Staticfile.auth ]]; then
   status "Enabling basic authentication"
@@ -60,14 +57,16 @@ if [[ -f Staticfile.auth ]]; then
   echo
   protip "Learn about basic authentication" "https://github.com/drnic/staticfile-buildpack#basic-authentication"
 fi
-[[ -f $build_dir/public/nginx.conf ]] && mv $build_dir/public/nginx.conf openresty/nginx/conf/nginx.conf
-[[ -f $build_dir/public/mime.types ]] && mv $build_dir/public/mime.types openresty/nginx/conf/mime.types
 
 # Enable directory index
 if [[ "$(grep directory: Staticfile)X" != "X" ]]; then
   status "Enabling directory index for folders without index.html files"
-  touch openresty/nginx/conf/.enable_directory_index
+  touch nginx/conf/.enable_directory_index
 fi
 
+# install nginx agent
+# status "Setting up New Relic agent"
+# command -v yum >/dev/null 2>&1 || { echo >&2 "I require yum but it's not installed.  Aborting."; exit 1; }
+# yum install nginx-nr-agent
+
 cp $compile_buildpack_bin/boot.sh .
-cp $compile_buildpack_bin/get_env .
